### PR TITLE
Clear all setTimeout functions on componentWillUnmount

### PR DESCRIPTION
**Pull request by ghost**
This fix resolves the issue of the setTimeout still typing text after the component has been unmounted.

Resolves this error:
```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op. Please check the code for the Loading component.
```

### CODE REVIEW

**Comment by lansana** [comment]
Thanks for the fix! Sorry for any inconvenience.

**Comment by ghost** [comment]
No problem, thanks! Let me know when you publish to NPM!

**Comment by lansana** [comment]
Done! Let me know if all is good to go.

**Comment by ghost** [comment]
It works! Thanks for the quick turn around

**Pull request merged**
